FROM cgr.dev/chainguard/python:latest-dev@sha256:2c0fbbac86b72ebb4bfee15b64d8cd5fd6b49dfe7bb279b5c9f193198a84c1c9 AS build

WORKDIR /app

COPY pyproject.toml ./
COPY app ./app

RUN python -m venv /app/.venv
ENV PATH="/app/.venv/bin:${PATH}"

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir .

FROM cgr.dev/chainguard/python:latest@sha256:18a4fbda8c280978b6aa5329f7acd4dbb106876e76fdc87913855ebf4876f2ff

WORKDIR /app

COPY --from=build /app/.venv /app/.venv
COPY app ./app

ENV PATH="/app/.venv/bin:${PATH}" \
    PYTHONPATH="/app"

CMD ["python", "-m", "app.workers.normalizer"]
